apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: threat-api
  template:
    metadata:
      labels:
        app: threat-api
    spec:
      containers:
      - name: threat-api
        image: mattiyeshurun/threat-api:v1
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_USER
          value: "user"
        - name: DB_PASS
          value: "secret_password"
